using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public class UsernameGenerator
{

    private static readonly string[] MaleNouns = {
  "Abuelo",
  "Acento",
  "Actor",
  "Alumno",
  "Amigo",
  "Ángel",
  "Animal",
  "Anillo",
  "Astronauta",
  "Avión",
  "Árbol",
  "Arco",
  "Artista",
  "Barrio",
  "Bosque",
  "Banco",
  "Barco",
  "Botón",
  "Brazo",
  "Caballo",
  "Camino",
  "Campo",
  "Cantante",
  "Capitán",
  "Caramelo",
  "Carpintero",
  "Carro",
  "Cartero",
  "Cartel",
  "Caso",
  "Castillo",
  "Cazador",
  "Celular",
  "Centro",
  "Cerebro",
  "Chico",
  "Chocolate",
  "Ciclista",
  "Cielo",
  "Ciervo",
  "Cine",
  "Cineasta",
  "Circulo",
  "Cirujano",
  "Clavo",
  "Coche",
  "Cocinero",
  "Cohete",
  "Color",
  "Colegio",
  "Cometa",
  "Concierto",
  "Conde",
  "Conductor",
  "Conejo",
  "Conjunto",
  "Consejero",
  "Constructor",
  "Contador",
  "Control",
  "Corazón",
  "Coro",
  "Correo",
  "Creador",
  "Cristal",
  "Cuaderno",
  "Cuadro",
  "Cuerpo",
  "Cuento",
  "Cultivo",
  "Danzarín",
  "Dedo",
  "Delfín",
  "Dente",
  "Dentista",
  "Deporte",
  "Desayuno",
  "Desierto",
  "Diamante",
  "Diente",
  "Dibujo",
  "Dinosaurio",
  "Director",
  "Disco",
  "Doctor",
  "Dolor",
  "Dominó",
  "Documento",
  "Dragón",
  "Eco",
  "Edificio",
  "Ejército",
  "Electricista",
  "Elefante",
  "Empleado",
  "Emperador",
  "Enano",
  "Enemigo",
  "Enfermero",
  "Enigma",
  "Escalón",
  "Escolar",
  "Escorpión",
  "Escritor",
  "Espacio",
  "Espectro",
  "Espejo",
  "Espía",
  "Estadio",
  "Estanque",
  "Estilo",
  "Estudiante",
  "Estudio",
  "Explorador",
  "Faro",
  "Fantasma",
  "Festival",
  "Fósforo",
  "Fotógrafo",
  "Frío",
  "Fuego",
  "Futbolista",
  "Galaxia",
  "Gallo",
  "Ganador",
  "Garaje",
  "Gato",
  "Genio",
  "Gigante",
  "Globo",
  "Glóbulo",
  "Gol",
  "Golfo",
  "Gorila",
  "Grabado",
  "Grano",
  "Grupo",
  "Guante",
  "Guerrero",
  "Gusano",
  "Helado",
  "Hermano",
  "Héroe",
  "Hielo",
  "Hierro",
  "Hijo",
  "Hilo",
  "Hipnotizador",
  "Historiador",
  "Hogar",
  "Hombre",
  "Hormigón",
  "Hotel",
  "Huésped",
  "Huevo",
  "Humo",
  "Huracán",
  "Húsar",
  "Idioma",
  "Ídolo",
  "Imán",
  "Imperio",
  "Impresor",
  "Indio",
  "Ingeniero",
  "Insecto",
  "Inventario",
  "Investigador",
  "Jabalí",
  "Jardín",
  "Jinete",
  "Juego",
  "Jugador",
  "Juguete",
  "Laberinto",
  "Laboratorio",
  "Ladrón",
  "Lago",
  "Lápiz",
  "León",
  "Líder",
  "Lince",
  "Libro",
  "Loco",
  "Luchador",
  "Magistrado",
  "Magno",
  "Maíz",
  "Malecón",
  "Manantial",
  "Mando",
  "Mango",
  "Maniquí",
  "Mapa",
  "Mar",
  "Marciano",
  "Mármol",
  "Martillo",
  "Mártir",
  "Máscara",
  "Maestro",
  "Mecánico",
  "Medallón",
  "Médico",
  "Mendigo",
  "Mensajero",
  "Mercado",
  "Mérito",
  "Metal",
  "Meteorito",
  "Microbio",
  "Microscopio",
  "Militar",
  "Minero",
  "Ministro",
  "Mito",
  "Modisto",
  "Módulo",
  "Mono",
  "Monstruo",
  "Monte",
  "Monumento",
  "Morro",
  "Moto",
  "Motor",
  "Muelle",
  "Mundo",
  "Mural",
  "Muro",
  "Músico",
  "Nabo",
  "Nariz",
  "Nave",
  "Nebuloso",
  "Nieto",
  "Nivel",
  "Noble",
  "Nodo",
  "Nómada",
  "Número",
  "Objeto",
  "Observador",
  "Océano",
  "Octágono",
  "Oficial",
  "Óleo",
  "Ópera",
  "Opinión",
  "Orador",
  "Orbe",
  "Ordenador",
  "Oso",
  "Ovni",
  "Pájaro",
  "Palacio",
  "Pantalón",
  "Papel",
  "Paracaídas",
  "Parásito",
  "Parque",
  "Pasajero",
  "Pato",
  "Pavo",
  "Paz",
  "Péndulo",
  "Pensador",
  "Perfume",
  "Periódico",
  "Perro",
  "Pescador",
  "Pez",
  "Piano",
  "Pico",
  "Piloto",
  "Pintor",
  "Pirámide",
  "Pirata",
  "Pistón",
  "Planeta",
  "Plátano",
  "Plato",
  "Playa",
  "Poeta",
  "Polvo",
  "Poncho",
  "Portero",
  "Postre",
  "Prado",
  "Príncipe",
  "Prisma",
  "Problema",
  "Productor",
  "Profesor",
  "Programador",
  "Proyecto",
  "Puente",
  "Pulmón",
  "Pulpo",
  "Punto",
  "Quebracho",
  "Radiotelescopio",
  "Ratón",
  "Rayo",
  "Reactor",
  "Receptor",
  "Recuerdo",
  "Red",
  "Reflejo",
  "Regalo",
  "Reloj",
  "Remo",
  "Reptil",
  "Resorte",
  "Retrato",
  "Rey",
  "Río",
  "Robot",
  "Rocío",
  "Rollo",
  "Rompecabezas",
  "Ruiseñor",
  "Sabio",
  "Sable",
  "Sacerdote",
  "Saco",
  "Sagrado",
  "Salto",
  "Santuario",
  "Satélite",
  "Secreto",
  "Seguidor",
  "Selva",
  "Semáforo",
  "Señal",
  "Señor",
  "Serpiente",
  "Servidor",
  "Sexo",
  "Siglo",
  "Silencio",
  "Símbolo",
  "Simio",
  "Sistema",
  "Sitio",
  "Socio",
  "Soldado",
  "Sol",
  "Sombra",
  "Sonido",
  "Sordo",
  "Sueño",
  "Superhéroe",
  "Susurro",
  "Tabaco",
  "Tabla",
  "Tablero",
  "Taco",
  "Talento",
  "Taller",
  "Tambor",
  "Tango",
  "Tanque",
  "Tapón",
  "Tarro",
  "Teatro",
  "Técnico",
  "Tejido",
  "Teléfono",
  "Televisor",
  "Temblor",
  "Templo",
  "Tenedor",
  "Tenis",
  "Tenor",
  "Tequila",
  "Terapeuta",
  "Terremoto",
  "Territorio",
  "Tesoro",
  "Tiburón",
  "Tiempo",
  "Tigre",
  "Títere",
  "Título",
  "Tobillo",
  "Tocado",
  "Toro",
  "Torpedo",
  "Torre",
  "Tractor",
  "Trago",
  "Tranvía",
  "Tratado",
  "Tren",
  "Triángulo",
  "Trono",
  "Trovador",
  "Tubo",
  "Tumor",
  "Túnel",
  "Turista",
  "Tutor",
  "Último",
  "Uniforme",
  "Universo",
  "Urano",
  "Urgente",
  "Uso",
  "Vagón",
  "Valiente",
  "Valle",
  "Vampiro",
  "Vapor",
  "Varón",
  "Vehículo",
  "Velero",
  "Vendedor",
  "Veneno",
  "Ventana",
  "Verano",
  "Verde",
  "Verso",
  "Viaje",
  "Víbora",
  "Vicio",
  "Víctima",
  "Video",
  "Viejo",
  "Viento",
  "Vikingo",
  "Villano",
  "Vinilo",
  "Violín",
  "Virus",
  "Visión",
  "Vital",
  "Vocablo",
  "Volumen",
  "Vuelo",
  "Yate",
  "Yogur",
  "Zapato",
  "Zar",
  "Zoológico",
  "Zorro"
};

    private static readonly string[] FemaleNouns = {
  "Abeja",
  "Abrazo",
  "Abuela",
  "Aceptación",
  "Acuarela",
  "Admiración",
  "Aguja",
  "Ala",
  "Aldea",
  "Alegría",
  "Alfombra",
  "Almendra",
  "Alondra",
  "Almohada",
  "América",
  "Amistad",
  "Anécdota",
  "Angel",
  "Anillo",
  "Ansiedad",
  "Antena",
  "Antorcha",
  "Araña",
  "Araucaria",
  "Arena",
  "Arboleda",
  "Arcilla",
  "Aria",
  "Armonía",
  "Arpillera",
  "Arte",
  "Artista",
  "Ascensión",
  "Asignatura",
  "Atmósfera",
  "Aura",
  "Aventura",
  "Ave",
  "Avellana",
  "Azucena",
  "Azúcar",
  "Bacteria",
  "Bahía",
  "Bandera",
  "Baraja",
  "Barrera",
  "Batalla",
  "Baya",
  "Belleza",
  "Berlina",
  "Biblia",
  "Biblioteca",
  "Bicicleta",
  "Bienvenida",
  "Bisagra",
  "Bodega",
  "Bohemia",
  "Bolsa",
  "Bóveda",
  "Brasa",
  "Brillantez",
  "Brújula",
  "Bruja",
  "Burbuja",
  "Cabaña",
  "Cabellera",
  "Cabina",
  "Cacerola",
  "Caja",
  "Calabaza",
  "Calcomanía",
  "Caldera",
  "Cáliz",
  "Calle",
  "Cámara",
  "Camelia",
  "Campana",
  "Campanilla",
  "Campiña",
  "Canasta",
  "Canción",
  "Canela",
  "Cantante",
  "Capilla",
  "Caracola",
  "Caravana",
  "Carcasa",
  "Careta",
  "Carmesí",
  "Carrera",
  "Carretera",
  "Carta",
  "Cartelera",
  "Casa",
  "Cascada",
  "Caseta",
  "Castaña",
  "Catedral",
  "Catástrofe",
  "Caverna",
  "Cebra",
  "Cebolla",
  "Cenicienta",
  "Ceniza",
  "Cera",
  "Ceremonia",
  "Cereza",
  "Cervecería",
  "Cerveza",
  "Chispa",
  "Ciudad",
  "Cicatriz",
  "Cigüeña",
  "Cima",
  "Ciruela",
  "Cirugía",
  "Ciudadanía",
  "Clase",
  "Clavícula",
  "Clemecia",
  "Cocina",
  "Colina",
  "Colmena",
  "Columna",
  "Cometa",
  "Compasión",
  "Computadora",
  "Concha",
  "Conexión",
  "Constancia",
  "Constelación",
  "Contienda",
  "Continente",
  "Contraseña",
  "Coraza",
  "Corbeta",
  "Cordillera",
  "Corona",
  "Cosecha",
  "Costa",
  "Costumbre",
  "Cotorra",
  "Credencial",
  "Crisantemo",
  "Cristalería",
  "Cuadernilla",
  "Cubierta",
  "Cuchara",
  "Cuchillería",
  "Cuenca",
  "Cuerda",
  "Cumbre",
  "Curva",
  "Dama",
  "Danza",
  "Dádiva",
  "Dalia",
  "Dársena",
  "Década",
  "Decisión",
  "Dedicatoria",
  "Defensa",
  "Deidad",
  "Demanda",
  "Democracia",
  "Densidad",
  "Despedida",
  "Destreza",
  "Diadema",
  "Diamante",
  "Diapositiva",
  "Dicha",
  "Dinastía",
  "Diplomacia",
  "Dirección",
  "Disciplina",
  "Discreción",
  "Disertación",
  "Distancia",
  "Divinidad",
  "Doctrina",
  "Dote",
  "Duda",
  "Dulzura",
  "Economía",
  "Edad",
  "Edición",
  "Educación",
  "Efigie",
  "Efusión",
  "Elegancia",
  "Elevación",
  "Elipse",
  "Embajada",
  "Embarcación",
  "Embrujada",
  "Emergencia",
  "Empatía",
  "Empresa",
  "Encomienda",
  "Enfermedad",
  "Enigma",
  "Entidad",
  "Entrada",
  "Epístola",
  "Equidad",
  "Era",
  "Escala",
  "Escalera",
  "Escena",
  "Esencia",
  "Esfera",
  "Esperanza",
  "Esplendor",
  "Espada",
  "Estampa",
  "Estación",
  "Estatua",
  "Estrategia",
  "Estrella",
  "Estrofa",
  "Eternidad",
  "Etiqueta",
  "Euforia",
  "Evocación",
  "Exaltación",
  "Excepción",
  "Expedición",
  "Experiencia",
  "Explicación",
  "Explosión",
  "Exposición",
  "Extensión",
  "Fachada",
  "Familia",
  "Fantasía",
  "Farola",
  "Farsa",
  "Fase",
  "Fe",
  "Felicidad",
  "Feria",
  "Ferocidad",
  "Fertilidad",
  "Festividad",
  "Ficha",
  "Fidelidad",
  "Figura",
  "Firma",
  "Fisura",
  "Flama",
  "Flecha",
  "Fobia",
  "Fogata",
  "Fórmula",
  "Fortaleza",
  "Fortuna",
  "Fotografía",
  "Fragancia",
  "Franja",
  "Frecuencia",
  "Frescura",
  "Frontera",
  "Fruta",
  "Fuga",
  "Función",
  "Fundación",
  "Furia",
  "Galería",
  "Gama",
  "Garganta",
  "Garra",
  "Gaviota",
  "Gema",
  "Generación",
  "Génesis",
  "Gente",
  "Geografía",
  "Gerbera",
  "Gloria",
  "Glosa",
  "Golondrina",
  "Gota",
  "Gracia",
  "Granada",
  "Gratitud",
  "Gravilla",
  "Guitarra",
  "Habitación",
  "Hacienda",
  "Harmonía",
  "Hazaña",
  "Helada",
  "Hendidura",
  "Herencia",
  "Hermana",
  "Heroína",
  "Herradura",
  "Herramienta",
  "Hiedra",
  "Hija",
  "Hilera",
  "Historia",
  "Hoguera",
  "Hoja",
  "Hondonada",
  "Hora",
  "Huella",
  "Humanidad",
  "Humildad",
  "Idea",
  "Identidad",
  "Ilusión",
  "Imagen",
  "Imperfección",
  "Impresión",
  "Incertidumbre",
  "Industria",
  "Infancia",
  "Infinidad",
  "Influencia",
  "Iniciativa",
  "Insignia",
  "Inspección",
  "Inspiración",
  "Instancia",
  "Instrucción",
  "Integración",
  "Intensidad",
  "Interacción",
  "Interfaz",
  "Internacional",
  "Interpretación",
  "Intervención",
  "Intimidad",
  "Intriga",
  "Intuición",
  "Inundación",
  "Invasión",
  "Investigación",
  "Invitación",
  "Iris",
  "Ironía",
  "Isla",
  "Jabonera",
  "Jaula",
  "Jirafa",
  "Jubilación",
  "Jugada",
  "Juglaría",
  "Jungla",
  "Jurisdicción",
  "Justicia",
  "Juventud",
  "Kermés",
  "Lágrima",
  "Lamentación",
  "Lámpara",
  "Lancha",
  "Lanza",
  "Larva",
  "Lectura",
  "Legumbre",
  "Lejanía",
  "Lengua",
  "Lesión",
  "Letra",
  "Levedad",
  "Libertad",
  "Librería",
  "Licencia",
  "Línea",
  "Llama",
  "Lluvia",
  "Loma",
  "Luminosidad",
  "Luna",
  "Lunada",
  "Madre",
  "Madurez",
  "Magia",
  "Magnolia",
  "Majestuosidad",
  "Malicia",
  "Manada",
  "Manantial",
  "Mancha",
  "Mandarina",
  "Manga",
  "Maniobra",
  "Mansión",
  "Manta",
  "Manualidad",
  "Maquillaje",
  "Maravilla",
  "Marca",
  "Marimba",
  "Mariposa",
  "Máscara",
  "Materia",
  "Medalla",
  "Medida",
  "Melancolía",
  "Melodía",
  "Memoria",
  "Mención",
  "Mentira",
  "Merienda",
  "Meseta",
  "Metrópoli",
  "Miel",
  "Migaja",
  "Milagro",
  "Milla",
  "Mimosa",
  "Minería",
  "Mirada",
  "Misión",
  "Mística",
  "Mitología",
  "Moda",
  "Molécula",
  "Monarquía",
  "Moneda",
  "Montaña",
  "Motivación",
  "Motorización",
  "Muñeca",
  "Naranja",
  "Naturaleza",
  "Noche",
  "Nube",
  "Oportunidad",
  "Palabra",
  "Pantalla",
  "Paz",
  "Película",
  "Piedra",
  "Pierna",
  "Pirámide",
  "Planta",
  "Playa",
  "Poesía",

  "Zanahoria",
  "Zapatilla"
};

    private static readonly string[] MaleAdjectives = {
    "Valiente", "Fuerte", "Rápido", "Inteligente", "Audaz", "Leal",
    "Amable", "Generoso", "Decidido", "Eficaz", "Trabajador", "Respetuoso",
    "Honesto", "Optimista", "Creativo", "Paciente", "Persistente", "Valeroso",
    "Innovador", "Entusiasta", "Dinámico", "Sincero", "Emprendedor", "Amistoso",
    "Atento", "Cortés", "Flexible", "Dedicado", "Metódico", "Organizado",
    "Responsable", "Cuidadoso", "Práctico", "Objetivo", "Analítico", "Curioso",
    "Ágil", "Activo", "Ponderado", "Educado", "Elegante", "Estilizado",
    "Sensato", "Prudente", "Humilde", "Modesto", "Compasivo",
    "Aventurero", "Vigoroso", "Inspirador", "Apasionado", "Romántico", "Cálido",
    "Carismático", "Encantador", "Ingenioso", "Intrépido", "Jovial", "Juguetón",
    "Observador", "Perspicaz", "Reflexivo", "Sagaz", "Sereno",
    "Simpático", "Sociable", "Solícito", "Soñador", "Tolerante", "Tranquilo",
    "Versátil", "Visionario", "Afectuoso", "Bondadoso", "Cauto", "Concienzudo",
    "Cordial", "Despierto", "Diligente", "Discreto", "Ecuánime", "Equilibrado",
    "Erudito", "Esforzado", "Estudioso", "Exigente", "Expeditivo", "Expresivo",
    "Fiel", "Formal", "Fraterno", "Gentil", "Gracioso", "Hábil", "Ilustrado",
    "Imaginativo", "Imparcial", "Inquebrantable", "Integro", "Juicioso", "Laborioso"
};

    private static readonly string[] FemaleAdjectives = {
    "Valiente", "Fuerte", "Rápida", "Inteligente", "Audaz", "Leal",
    "Amable", "Generosa", "Decidida", "Eficaz", "Trabajadora", "Respetuosa",
    "Honesta", "Optimista", "Creativa", "Paciente", "Persistente", "Valerosa",
    "Innovadora", "Entusiasta", "Dinámica", "Sincera", "Emprendedora", "Amistosa",
    "Atenta", "Cortés", "Flexible", "Dedicada", "Metódica", "Organizada",
    "Responsable", "Cuidadosa", "Práctica", "Objetiva", "Analítica", "Curiosa",
    "Ágil", "Activa", "Ponderada", "Educada", "Elegante", "Estilizada",
    "Sensata", "Prudente", "Humilde", "Modesta", "Compasiva", "Comprensiva",
    "Aventurera", "Vigorosa", "Inspiradora", "Apasionada", "Romántica", "Cálida",
    "Carismática", "Encantadora", "Ingeniosa", "Intrépida", "Jovial", 
    "Observadora", "Perspicaz", "Reflexiva", "Sagaz", "Serena",
    "Simpática", "Sociable", "Solícita", "Soñadora", "Tolerante", "Tranquila",
    "Versátil", "Visionaria", "Afectuosa", "Bondadosa", "Cauta", "Concienzuda",
    "Cordial", "Despierta", "Diligente", "Discreta", "Ecuánime", "Equilibrada",
    "Erudita", "Esforzada", "Estudiosa", "Exigente", "Expeditiva", "Expresiva",
    "Fiel", "Formal", "Fraternal", "Gentil", "Graciosa", "Hábil", "Ilustrada",
    "Imaginativa", "Imparcial", "Inquebrantable", "Íntegra", "Juiciosa", "Laboriosa"
};

    private static readonly string[] MaleOrdinals = {
    "", "Segundo", "Tercero", "Cuarto", "Quinto", "Sexto", "Séptimo", "Octavo", "Noveno", "Décimo",
    "11o", "12o", "13o", "14o", "15o", "16o", "17o", "18o", "19o", "20o",
    "21o", "22o", "23o", "24o", "25o", "26o", "27o", "28o", "29o", "30o",
    "31o", "32o", "33o", "34o", "35o", "36o", "37o", "38o", "39o", "40o",
    "41o", "42o", "43o", "44o", "45o", "46o", "47o", "48o", "49o", "50o",
    "51o", "52o", "53o", "54o", "55o", "56o", "57o", "58o", "59o", "60o",
    "61o", "62o", "63o", "64o", "65o", "66o", "67o", "68o", "69o", "70o",
    "71o", "72o", "73o", "74o", "75o", "76o", "77o", "78o", "79o", "80o",
    "81o", "82o", "83o", "84o", "85o", "86o", "87o", "88o", "89o", "90o",
    "91o", "92o", "93o", "94o", "95o", "96o", "97o", "98o", "99o",  "Centésimo"
};

    private static readonly string[] FemaleOrdinals = {
    "", "Segunda", "Tercera", "Cuarta", "Quinta", "Sexta", "Séptima", "Octava", "Novena", "Décima",
    "11a", "12a", "13a", "14a", "15a", "16a", "17a", "18a", "19a", "20a",
    "21a", "22a", "23a", "24a", "25a", "26a", "27a", "28a", "29a", "30a",
    "31a", "32a", "33a", "34a", "35a", "36a", "37a", "38a", "39a", "40a",
    "41a", "42a", "43a", "44a", "45a", "46a", "47a", "48a", "49a", "50a",
    "51a", "52a", "53a", "54a", "55a", "56a", "57a", "58a", "59a", "60a",
    "61a", "62a", "63a", "64a", "65a", "66a", "67a", "68a", "69a", "70a",
    "71a", "72a", "73a", "74a", "75a", "76a", "77a", "78a", "79a", "80a",
    "81a", "82a", "83a", "84a", "85a", "86a", "87a", "88a", "89a", "90a",
    "91a", "92a", "93a", "94a", "95a", "96a", "97a", "98a", "99a", "Centésima"
};




    public static int GetTotalCombinations()
    {
        int masculineCombinations = MaleNouns.Length * MaleAdjectives.Length * MaleOrdinals.Length;
        int feminineCombinations = FemaleNouns.Length * FemaleAdjectives.Length * FemaleOrdinals.Length;
        return masculineCombinations + feminineCombinations;
    }
    private static void CheckForDuplicates(string[] array, string arrayName)
    {
        var duplicates = array.GroupBy(x => x)
                              .Where(g => g.Count() > 1)
                              .Select(y => y.Key)
                              .ToList();

        if (duplicates.Count > 0)
        {
            throw new Exception($"Duplicates detected in {arrayName}: {string.Join(", ", duplicates)}");
        }
    }
    /// <summary>
    /// Code to test that all the usernames are unique
    /// </summary>
    /// <exception cref="Exception"></exception>
    public static void Test()
    {
        CheckForDuplicates(MaleNouns, nameof(MaleNouns));
        CheckForDuplicates(FemaleNouns, nameof(FemaleNouns));
        CheckForDuplicates(MaleAdjectives, nameof(MaleAdjectives));
        CheckForDuplicates(FemaleAdjectives, nameof(FemaleAdjectives));

        if (MaleNouns.Length != FemaleNouns.Length)
        {
            throw new Exception($"The lengths of male and female noun arrays are not equal. Male nouns count: {MaleNouns.Length}, Female nouns count: {FemaleNouns.Length}.");
        }
        else if (MaleAdjectives.Length != FemaleAdjectives.Length)
        {
            throw new Exception($"The lengths of male and female adjective arrays are not equal. Male adjectives count: {MaleAdjectives.Length}, Female adjectives count: {FemaleAdjectives.Length}.");
        }
        else if (MaleOrdinals.Length != FemaleOrdinals.Length)
        {
            throw new Exception($"The lengths of male and female ordinal arrays are not equal. Male ordinals count: {MaleOrdinals.Length}, Female ordinals count: {FemaleOrdinals.Length}.");
        }

     
        var permutations = GetTotalCombinations();

        HashSet<string> names = new HashSet<string>();
        for (int i = 0; i < permutations; i++)
        {
            var currentName = GenerateUsernameFromUserCount(i);
   
            if (!names.Add(currentName)) // Add returns false if the element is already present
            {
                throw new Exception($"Duplicate name detected: '{currentName}' at index {i}");
            }
        }


        Debug.Log(string.Join(", ", names));
        Debug.Log($"{permutations} combinations");
    }


    // TODO: We need to calculate the indices to generate the username. We have to alternate between male and female, so the first is ElPrimerAbueloValiente, then we alternate to a female, which would give us LaPrimeraAbuelaValiente.
    public static string GenerateUsernameFromUserCount(int index)
    {
        bool isMale = index % 2 == 0; // Alternate between male and female
        int totalNouns = isMale ? MaleNouns.Length : FemaleNouns.Length;
        int totalAdjectives = isMale ? MaleAdjectives.Length : FemaleAdjectives.Length;
        int totalOrdinals = isMale ? MaleOrdinals.Length : FemaleOrdinals.Length;

        int nounIndex = (index / 2) % totalNouns;
        int adjectiveIndex = ((index / 2) / totalNouns) % totalAdjectives;
        int ordinalIndex = (((index / 2) / totalNouns) / totalAdjectives) % totalOrdinals;

        string username = isMale ? "El" : "La";

        if (isMale)
        {
            username += MaleOrdinals[ordinalIndex] + MaleNouns[nounIndex] + MaleAdjectives[adjectiveIndex];
        }
        else
        {
            username += FemaleOrdinals[ordinalIndex] + FemaleNouns[nounIndex] + FemaleAdjectives[adjectiveIndex];
        }

        return username;
    }



}